### ISSUE TITLE
How to campling kernel

### ISSUE THREAD

**Issue by smileyNeha** [realme-kernel-opensource/realme7_narzo20pro_AndroidQ-kernel-source#1]
Hello , 
How to campling kernel

**Comment by ZIDAN44** [comment]
By using compiler :D

**Comment by techyminati** [comment]
> By using compiler :D

+1

**Comment by smileyNeha** [comment]
> By using compiler :D

Thank you sir 😊

**Comment by Hunter-commits** [comment]
> By using compiler :D

😂😂😂

**Comment by NitroVenom** [comment]
What's campling?

**Comment by Ramisky** [comment]
> Hello ,
> How to campling kernel

Good question, but you didn't bother to ask how is campling kernel, feelings yk

**Comment by ironmerc** [comment]
> Hello ,
> How to campling kernel

Camp and compile

**Comment by nadinsylaa** [comment]
Lamwak

**Comment by denomparkour** [comment]
angel priya alt lmao

**Comment by shark1369** [comment]
Lmao🤣

**Comment by herobuxx** [comment]
> By using compiler :D

No bro, use campler instead

**Comment by adi8900** [comment]
Lmao, you need camembert for build

**Comment by SALMANKHANPM** [comment]
> Hello ,
> How to campling kernel

lol ! correct the spelling

**Comment by LinkBoi00** [comment]
Meme people compile meme kernels

**Comment by Velosh** [comment]
Lmao
